/* Wildlands Mod Framework / Immersion Suite fork.
 * Original GRW ScriptHook portions Copyright (C) 2026 PhialsBasement.
 * Modifications and additions Copyright (C) 2026 iDarkslay.
 * Modified through 2026-09-12. SPDX-License-Identifier: GPL-3.0-only.
 * See LICENSE, NOTICE.md and UPSTREAM_CHANGES.md.
 */
/* Entity enumeration, static paths only. Each entity
 * carries one component whose CLASS is its type.
 */
#include <windows.h>
#include <string.h>
#include <stdint.h>
#include <math.h>

#define SH_BUILD 1
#include "scripthook.h"
#include "image.h"

/* RVAs, so this survives a relocated image. */
#define RVA_PLAYER_MGR   0x4BB6438
#define RVA_VT_ENTITY    0x39C6FC8

#define OFF_MGR_WORLD    0x98
#define OFF_WORLD_LIST   0xBA0
#define OFF_WORLD_COUNT  0xBA8
#define OFF_ENT_POS      0x50
#define OFF_ENT_COMPS    0x78
#define OFF_ENT_NCOMPS   0x82
#define VT_GETDESC       0x30
#define OFF_DESC_HASH    0x24
#define OFF_ENT_NODE     0x18
#define OFF_NODE_LINK    0x68

extern int ShReadableAddr(uint64_t addr, size_t len);
extern int ShReadMem(uint64_t addr, void *out, size_t len);
extern uint64_t ShReadQ(uint64_t addr);
extern void ShSetError(int err);
extern int ShRequireInGame(void);
extern int ShGetHealthEntity(uint64_t entity, uint32_t *cur,
                             uint32_t *max);

static uint64_t ImgAddr(uint64_t rva) {
    return (uint64_t)(uintptr_t)GetModuleHandleA(NULL) + rva;
}

/* Link type 0 means no parent, so this is a root. Any
 * other type makes it a limb of something already listed.
 */
static int IsRoot(uint64_t entity) {
    uint64_t node;
    uint32_t type = 0;

    node = ShReadQ(entity + OFF_ENT_NODE);
    if (!node || !ShReadableAddr(node + OFF_NODE_LINK, 4)) return 1;
    memcpy(&type, (void *)(uintptr_t)(node + OFF_NODE_LINK), 4);
    return (type != 1 && type != 2);
}

/* Generated by nettypes.py from the image strings. */
static const struct {
    uint32_t hash;
    int kind;
    const char *name;
} g_kinds[] = {
    { 0x507DC2ECu, SH_KIND_PLAYER,    "Player"          },
    { 0xFEE4759Au, SH_KIND_NPC,       "NPC"             },
    { 0x8F2CBBBAu, SH_KIND_VEHICLE,   "Vehicle"         },
    { 0x5D621856u, SH_KIND_DRONE,     "Drone"           },
    { 0xEF953B76u, SH_KIND_TEAMMATE,  "Teammate"        },
    { 0x0186C7ACu, SH_KIND_TURRET,    "Turret"          },
    { 0xE6DBCF6Bu, SH_KIND_MINE,      "Mine"            },
    { 0x059648D5u, SH_KIND_DOOR,      "Door"            },
    { 0xCC586D4Au, SH_KIND_LOOTCHEST, "LootChest"       },
    { 0xA69E4386u, SH_KIND_OTHER,     "AlarmNet"        },
    { 0x7EDAAB74u, SH_KIND_OTHER,     "BearTrap"        },
    { 0x5644C87Fu, SH_KIND_OTHER,     "Codes"           },
    { 0xD839E268u, SH_KIND_OTHER,     "Destructible"    },
    { 0xD571F90Au, SH_KIND_OTHER,     "DominationPoint" },
    { 0xEB9D9BC9u, SH_KIND_OTHER,     "DroneJammer"     },
    { 0xFC1DFB0Du, SH_KIND_OTHER,     "Dummy"           },
    { 0x84C5EE35u, SH_KIND_OTHER,     "DynamicEvent"    },
    { 0xB22CC0B5u, SH_KIND_OTHER,     "EMPBlast"        },
    { 0xCAE95025u, SH_KIND_OTHER,     "ElectricDevice"  },
    { 0xB6E07575u, SH_KIND_OTHER,     "ExtractionPoint" },
    { 0x7B8D1BCDu, SH_KIND_OTHER,     "Flare"           },
    { 0xD19EB2D4u, SH_KIND_OTHER,     "FlareGun"        },
    { 0x19362348u, SH_KIND_OTHER,     "HackedServer"    },
    { 0x1F4B1328u, SH_KIND_OTHER,     "InteractiveElem" },
    { 0x4029E6AEu, SH_KIND_OTHER,     "LightPanel"      },
    { 0xA23FCD3Du, SH_KIND_OTHER,     "MagSensorNade"   },
    { 0x7C1D8BE9u, SH_KIND_OTHER,     "MercenaryAmmo"   },
    { 0x86EB450Au, SH_KIND_OTHER,     "MercAttachment"  },
    { 0x8D7F33FCu, SH_KIND_OTHER,     "MercCountable"   },
    { 0x8C89D0DDu, SH_KIND_OTHER,     "MercenaryItem"   },
    { 0x35A02C34u, SH_KIND_OTHER,     "MercenaryLoot"   },
    { 0x4433B66Au, SH_KIND_OTHER,     "MercenaryWeapon" },
    { 0x2F0FA0B5u, SH_KIND_OTHER,     "MineAdv"         },
    { 0x868D075Fu, SH_KIND_OTHER,     "Mortar"          },
    { 0xDA86CE85u, SH_KIND_OTHER,     "OrdersBeacon"    },
    { 0x04877609u, SH_KIND_OTHER,     "PVPHostage"      },
    { 0xCA10AECDu, SH_KIND_OTHER,     "PVPPrisonCell"   },
    { 0xF9789C28u, SH_KIND_OTHER,     "PlayerLoot"      },
    { 0xE162A6A3u, SH_KIND_OTHER,     "RCED"            },
    { 0xB631BC8Cu, SH_KIND_OTHER,     "RCEDAdv"         },
    { 0xD3D3F022u, SH_KIND_OTHER,     "RemoteJammer"    },
    { 0x8FE59CC6u, SH_KIND_OTHER,     "ResourceDrop"    },
    { 0x3D328332u, SH_KIND_OTHER,     "ResupplyDrop"    },
    { 0x9DE70FD6u, SH_KIND_OTHER,     "SAMLauncher"     },
    { 0x8211F572u, SH_KIND_OTHER,     "SatComTracker"   },
    { 0x84299CADu, SH_KIND_OTHER,     "SearchLight"     },
    { 0x3591E249u, SH_KIND_OTHER,     "Throwable"       },
    { 0xAF802229u, SH_KIND_OTHER,     "Tool"            },
    { 0x5E2209ADu, SH_KIND_OTHER,     "Tripwire"        },
    { 0xF033F1E9u, SH_KIND_OTHER,     "WeaponDrop"      },
    { 0xB6BC2554u, SH_KIND_OTHER,     "WorldEvent"      },
};

#define NKINDS (int)(sizeof(g_kinds) / sizeof(g_kinds[0]))

/* vtable +0x30 thunks to a getter returning the class
 * descriptor, whose +0x24 holds the class hash.
 */
static uint32_t ClassHashOf(uint64_t obj) {
    uint64_t vt, thunk, tgt, desc;
    uint8_t b[16];
    int32_t rel, disp;
    uint32_t hash = 0;
    int i;

    if (!ShReadableAddr(obj, 8)) return 0;
    vt = ShReadQ(obj);
    if (!ShReadableAddr(vt + VT_GETDESC, 8)) return 0;
    thunk = ShReadQ(vt + VT_GETDESC);
    if (!ShReadableAddr(thunk, 8)) return 0;
    memcpy(b, (void *)(uintptr_t)thunk, 8);
    if (b[0] != 0xE9) return 0;
    memcpy(&rel, b + 1, 4);
    tgt = thunk + 5 + rel;
    if (!ShReadableAddr(tgt, 16)) return 0;
    memcpy(b, (void *)(uintptr_t)tgt, 16);
    for (i = 0; i + 7 <= 16; i++) {
        if (b[i] == 0x48 && b[i + 1] == 0x8B && b[i + 2] == 0x05) {
            memcpy(&disp, b + i + 3, 4);
            desc = ShReadQ(tgt + i + 7 + disp);
            if (ShReadableAddr(desc + OFF_DESC_HASH, 4))
                memcpy(&hash, (void *)(uintptr_t)
                       (desc + OFF_DESC_HASH), 4);
            return hash;
        }
    }
    return 0;
}

static int KindIndex(uint64_t entity) {
    uint64_t arr;
    uint16_t n = 0, i;
    int k;

    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadableAddr(entity + OFF_ENT_NCOMPS, 2))
        return -1;
    memcpy(&n, (void *)(uintptr_t)(entity + OFF_ENT_NCOMPS), 2);
    if (!n || n > 512) return -1;

    for (i = 0; i < n; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);
        uint32_t h;
        if (!c) continue;
        h = ClassHashOf(c);
        if (!h) continue;
        for (k = 0; k < NKINDS; k++)
            if (g_kinds[k].hash == h) return k;
    }
    return -1;
}

SH_API int ShGetComponents(uint64_t entity, ShComponent *out,
                           int max)
{
    uint64_t arr;
    uint16_t n = 0, i;
    int written = 0, k;

    if (!out || max <= 0) { ShSetError(SH_ERR_BAD_ARG); return 0; }
    if (!entity || !ShReadableAddr(entity, 0x90)) {
        ShSetError(SH_ERR_NOT_ENTITY);
        return 0;
    }
    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadableAddr(entity + OFF_ENT_NCOMPS, 2)) {
        ShSetError(SH_ERR_NO_CANDIDATE);
        return 0;
    }
    memcpy(&n, (void *)(uintptr_t)(entity + OFF_ENT_NCOMPS), 2);
    if (!n || n > 512) { ShSetError(SH_ERR_NO_CANDIDATE); return 0; }

    for (i = 0; i < n && written < max; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);
        if (!c) continue;
        memset(&out[written], 0, sizeof(out[written]));
        out[written].component = c;
        out[written].dataBlock = ShReadQ(c + 0x20);
        out[written].classHash = ClassHashOf(c);
        for (k = 0; k < NKINDS; k++) {
            if (g_kinds[k].hash != out[written].classHash) continue;
            strncpy(out[written].name, g_kinds[k].name,
                    sizeof(out[written].name) - 1);
            break;
        }
        written++;
    }
    return written;
}

/* Render nodes carry a visible bit at +0x54. Hiding is a
 * data write, so no engine call and no game thread needed.
 */
#define RENDER_CLASS  0xEC658D29u
#define NODE_FLAGS    0x54
#define NODE_HIDDEN   0x0004

/* Kernel read modify write: a node freed on another thread
 * fails cleanly instead of faulting or corrupting.
 */
static int NodeFlag(uint64_t node, int hidden) {
    uint16_t f;
    SIZE_T put = 0;

    if (!node || !ShReadMem(node + NODE_FLAGS, &f, 2)) return 0;
    f = hidden ? (uint16_t)(f | NODE_HIDDEN)
               : (uint16_t)(f & ~NODE_HIDDEN);
    if (!WriteProcessMemory(GetCurrentProcess(),
                            (void *)(uintptr_t)(node + NODE_FLAGS),
                            &f, 2, &put))
        return 0;
    return put == 2;
}

static int SetNodesHidden(uint64_t entity, int hidden, int *seen) {
    uint64_t arr;
    uint16_t n = 0, i;
    int touched = 0;

    if (!entity || !ShReadableAddr(entity, 0x90)) {
        ShSetError(SH_ERR_NOT_ENTITY);
        return 0;
    }
    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadMem(entity + OFF_ENT_NCOMPS, &n, 2)) {
        ShSetError(SH_ERR_NO_CANDIDATE);
        return 0;
    }
    if (!n || n > 512) { ShSetError(SH_ERR_NO_CANDIDATE); return 0; }

    for (i = 0; i < n; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);

        if (!c || ClassHashOf(c) != RENDER_CLASS) continue;
        if (!NodeFlag(c, hidden)) continue;
        if (seen) (*seen)++;
        touched++;
    }
    return touched;
}

/* The head is a part group the camera owns for ADS. Its
 * controller is found by which render nodes it holds. */
#define CTRL_VT SH_IMG(0x3bcb2a8)
#define CTRL_NODES  0x40
#define CTRL_COUNT  0x4A

static uint64_t g_headEnt = 0;
static uint64_t g_headCtrl = 0;

/* Both arrays land in two kernel reads and compare
 * locally. A syscall per element multiplied out to tens
 * of ms per candidate and lagged the whole frame. */
static int OwnsAnyNode(uint64_t ctrl, uint64_t entity) {
    uint64_t nodes[64], comps[512];
    uint64_t arr, carr;
    uint16_t n = 0, cn = 0, i, j;

    arr = ShReadQ(ctrl + CTRL_NODES);
    if (!arr || !ShReadMem(ctrl + CTRL_COUNT, &n, 2)) return 0;
    if (!n || n > 64) return 0;

    carr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!carr || !ShReadMem(entity + OFF_ENT_NCOMPS, &cn, 2))
        return 0;
    if (!cn || cn > 512) return 0;

    if (!ShReadMem(arr, nodes, (size_t)n * 8)) return 0;
    if (!ShReadMem(carr, comps, (size_t)cn * 8)) return 0;

    for (i = 0; i < n; i++) {
        if (!nodes[i]) continue;
        for (j = 0; j < cn; j++)
            if (comps[j] == nodes[i]) return 1;
    }
    return 0;
}

/* Few of these exist, so the sweep is short and the answer
 * is cached for the entity that asked. */
static int CtrlAlive(uint64_t ctrl, uint64_t entity) {
    if (!ctrl || !ShReadableAddr(ctrl, 0x70)) return 0;
    if (ShReadQ(ctrl) != CTRL_VT) return 0;
    return OwnsAnyNode(ctrl, entity);
}

static uint64_t FindHeadGroup(uint64_t entity) {
    MEMORY_BASIC_INFORMATION mbi;
    uint8_t *scan = (uint8_t *)0x10000;

    /* These are freed and recycled, so a cached pointer is
     * verified before it is trusted.
     */
    if (g_headEnt == entity && CtrlAlive(g_headCtrl, entity))
        return g_headCtrl;
    g_headEnt = 0;
    g_headCtrl = 0;

    while (VirtualQuery(scan, &mbi, sizeof(mbi))) {
        uint8_t *next = (uint8_t *)mbi.BaseAddress + mbi.RegionSize;
        if (next <= scan) break;
        if ((uint64_t)(uintptr_t)mbi.BaseAddress >= 0x800000000000ULL)
            break;
        if (mbi.State == MEM_COMMIT &&
            (mbi.Protect & PAGE_READWRITE) &&
            !(mbi.Protect & PAGE_GUARD)) {
            uint8_t *b = (uint8_t *)mbi.BaseAddress;
            size_t sz = mbi.RegionSize, o, k, got;

            /* Chunked kernel reads: a region decommitted
             * mid scan skips instead of faulting. Chunks
             * overlap so no candidate spans a seam. */
            static uint8_t buf[0x10000];

            for (o = 0; o + 0x50 <= sz;
                 o += sizeof(buf) - 0x50) {
                got = sz - o;
                if (got > sizeof(buf)) got = sizeof(buf);
                if (!ShReadMem((uint64_t)(uintptr_t)(b + o),
                               buf, got))
                    continue;
                for (k = 0; k + 0x50 <= got; k += 8) {
                    uint64_t vt;
                    memcpy(&vt, buf + k, 8);
                    if (vt != CTRL_VT) continue;
                    if (!OwnsAnyNode(
                            (uint64_t)(uintptr_t)(b + o + k),
                            entity))
                        continue;
                    g_headEnt = entity;
                    g_headCtrl = (uint64_t)(uintptr_t)(b + o + k);
                    return g_headCtrl;
                }
            }
        }
        scan = next;
    }
    return 0;
}

static int SetGroupHidden(uint64_t ctrl, int hidden, int *seen) {
    uint64_t arr = ShReadQ(ctrl + CTRL_NODES);
    uint16_t n = 0, i;
    int touched = 0;

    if (!arr || !ShReadableAddr(ctrl + CTRL_COUNT, 2)) return 0;
    memcpy(&n, (void *)(uintptr_t)(ctrl + CTRL_COUNT), 2);
    if (!n || n > 64) return 0;

    for (i = 0; i < n; i++) {
        uint64_t node = ShReadQ(arr + (uint64_t)i * 8);
        uint16_t f;

        if (!node || !ShReadableAddr(node + NODE_FLAGS, 2)) continue;
        if (seen) (*seen)++;
        memcpy(&f, (void *)(uintptr_t)(node + NODE_FLAGS), 2);
        f = hidden ? (uint16_t)(f | NODE_HIDDEN)
                   : (uint16_t)(f & ~NODE_HIDDEN);
        memcpy((void *)(uintptr_t)(node + NODE_FLAGS), &f, 2);
        touched++;
    }
    return touched;
}

/* The camera re-asserts visibility on the nodes it owns, so
 * a persistent override has to be rewritten every frame.
 */
#define VIS_HELD 64

static uint64_t g_visEnt[VIS_HELD];
static uint64_t g_visNode[VIS_HELD];
static uint64_t g_visSig[VIS_HELD];
static int      g_visWant[VIS_HELD];

/* Freed node memory stays readable, so a hold rewriting it
 * corrupts whatever lives there next. The vtable qword is
 * the identity check: recycling never reproduces it. */
static void HoldVisibility(uint64_t entity, uint64_t node,
                           int visible) {
    int i, free = -1;

    for (i = 0; i < VIS_HELD; i++) {
        if (g_visEnt[i] == entity && g_visNode[i] == node) {
            g_visWant[i] = visible;
            return;
        }
        if (!g_visEnt[i] && free < 0) free = i;
    }
    if (free < 0) return;
    g_visEnt[free] = entity;
    g_visNode[free] = node;
    g_visSig[free] = node ? ShReadQ(node) : 0;
    g_visWant[free] = visible;
}

/* node 0 releases every hold on the entity, so a caller can
 * undo whatever it did without tracking the parts. */
static void ReleaseVisibility(uint64_t entity, uint64_t node) {
    int i;

    for (i = 0; i < VIS_HELD; i++) {
        if (g_visEnt[i] != entity) continue;
        if (node && g_visNode[i] != node) continue;
        g_visEnt[i] = 0;
        g_visNode[i] = 0;
        g_visSig[i] = 0;
    }
}

/* One shot applications, run by the pump. Callers used to
 * write from their own threads and raced entity teardown,
 * caught live as the read fault at dinput8+0x63E5. */
#define VIS_ONCE 64

static uint64_t g_onceEnt[VIS_ONCE];
static uint64_t g_onceNode[VIS_ONCE];
static uint64_t g_onceSig[VIS_ONCE];
static int      g_onceWant[VIS_ONCE];

void ShVisibilityOnWorldReset(void) {
    memset(g_visEnt,0,sizeof(g_visEnt));
    memset(g_visNode,0,sizeof(g_visNode));
    memset(g_visSig,0,sizeof(g_visSig));
    memset(g_onceEnt,0,sizeof(g_onceEnt));
    memset(g_onceNode,0,sizeof(g_onceNode));
    memset(g_onceSig,0,sizeof(g_onceSig));
    /* Wildlands may reuse the same player entity address after a map
     * teleport while replacing its render controller and nodes.  Entity
     * equality therefore cannot validate this discovery cache across worlds. */
    g_headEnt = 0;
    g_headCtrl = 0;
}

/* A respawn can replace only the streamed visual node while preserving the
 * player entity address.  Camera plugins use this lightweight invalidation
 * to force the next head query to discover the replacement controller. */
SH_API void ShHeadNodesInvalidate(void) {
    g_headEnt = 0;
    g_headCtrl = 0;
}

static void QueueVisibility(uint64_t entity, uint64_t node,
                            int visible) {
    int i;

    for (i = 0; i < VIS_ONCE; i++) {
        if (g_onceEnt[i]) continue;
        g_onceNode[i] = node;
        g_onceSig[i] = node ? ShReadQ(node) : 0;
        g_onceWant[i] = visible;
        g_onceEnt[i] = entity;
        return;
    }
}


static int SetOneNode(uint64_t node, int hidden) {
    return NodeFlag(node, hidden);
}

/* Called from the camera detour, on the game thread, which
 * is where the engine stamps these bits back.
 */
void ShVisibilityPump(void) {
    int i, seen;

    for (i = 0; i < VIS_ONCE; i++) {
        if (!g_onceEnt[i]) continue;
        if (g_onceNode[i]) {
            if (ShReadQ(g_onceNode[i]) == g_onceSig[i])
                SetOneNode(g_onceNode[i], g_onceWant[i] ? 0 : 1);
        } else {
            seen = 0;
            SetNodesHidden(g_onceEnt[i], g_onceWant[i] ? 0 : 1,
                           &seen);
        }
        g_onceEnt[i] = 0;
        g_onceNode[i] = 0;
        g_onceSig[i] = 0;
    }

    for (i = 0; i < VIS_HELD; i++) {
        if (!g_visEnt[i]) continue;
        seen = 0;
        if (g_visNode[i]) {
            /* Readable is a weak test: recycled memory
             * still reads. The vtable must match too, or
             * the write lands in someone else's object. */
            if (ShReadQ(g_visNode[i]) != g_visSig[i]) {
                g_visEnt[i] = 0;
                g_visNode[i] = 0;
                g_visSig[i] = 0;
                continue;
            }
            seen = SetOneNode(g_visNode[i], g_visWant[i] ? 0 : 1);
        } else {
            SetNodesHidden(g_visEnt[i], g_visWant[i] ? 0 : 1, &seen);
        }
        /* A freed entity or node stops reading, so drop it
         * rather than writing into recycled memory.
         */
        if (!seen) {
            g_visEnt[i] = 0;
            g_visNode[i] = 0;
            g_visSig[i] = 0;
        }
    }
}

/* node 0 means every render node on the entity. persist
 * rewrites the bit each frame until it is shown again.
 */
/* Deferred: the pump applies on the game thread, in the
 * same window the engine stamps the bits. Writing on the
 * caller's thread raced entity teardown and corrupted. */
SH_API int ShSetVisible(uint64_t entity, uint64_t node,
                        int visible, int persist) {
    if (!entity) { ShSetError(SH_ERR_BAD_ARG); return 0; }

    if (persist && !visible) {
        HoldVisibility(entity, node, visible);
    } else {
        ReleaseVisibility(entity, node);
        QueueVisibility(entity, node, visible);
    }
    ShSetError(SH_OK);
    return 1;
}

/** Every render node on an entity. Returns how many. */
SH_API int ShGetEntityNodes(uint64_t entity, uint64_t *out,
                            int max) {
    uint64_t arr;
    uint16_t n = 0, i;
    int w = 0;

    if (!out || max <= 0) { ShSetError(SH_ERR_BAD_ARG); return 0; }
    if (!entity || !ShReadableAddr(entity, 0x90)) {
        ShSetError(SH_ERR_NOT_ENTITY);
        return 0;
    }
    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadableAddr(entity + OFF_ENT_NCOMPS, 2)) return 0;
    memcpy(&n, (void *)(uintptr_t)(entity + OFF_ENT_NCOMPS), 2);
    if (!n || n > 512) return 0;

    for (i = 0; i < n && w < max; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);
        if (c && ClassHashOf(c) == RENDER_CLASS) out[w++] = c;
    }
    ShSetError(SH_OK);
    return w;
}

/* The parts the camera hides for aiming, which on a
 * character is the head. Discovery, not a special case.
 */
/* Safe from any thread: every access is a kernel read, so
 * a page freed mid walk fails instead of faulting, and the
 * scan never touches the frame budget. */
SH_API int ShGetHeadNodes(uint64_t entity, uint64_t *out, int max) {
    uint64_t ctrl, arr, nodes[64];
    uint16_t n = 0, i;
    int w = 0;

    if (!out || max <= 0 || !entity) {
        ShSetError(SH_ERR_BAD_ARG);
        return 0;
    }
    ctrl = FindHeadGroup(entity);
    if (!ctrl) { ShSetError(SH_ERR_NO_CANDIDATE); return 0; }
    arr = ShReadQ(ctrl + CTRL_NODES);
    if (!arr || !ShReadMem(ctrl + CTRL_COUNT, &n, 2)) return 0;
    if (!n || n > 64) return 0;
    if (!ShReadMem(arr, nodes, (size_t)n * 8)) return 0;

    for (i = 0; i < n && w < max; i++)
        if (nodes[i]) out[w++] = nodes[i];
    ShSetError(SH_OK);
    return w;
}

/** How many render nodes an entity has, 0 if none. */
SH_API int ShEntityNodeCount(uint64_t entity) {
    uint64_t arr;
    uint16_t n = 0, i;
    int count = 0;

    if (!entity || !ShReadableAddr(entity, 0x90)) return 0;
    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadableAddr(entity + OFF_ENT_NCOMPS, 2)) return 0;
    memcpy(&n, (void *)(uintptr_t)(entity + OFF_ENT_NCOMPS), 2);
    if (!n || n > 512) return 0;
    for (i = 0; i < n; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);
        if (c && ClassHashOf(c) == RENDER_CLASS) count++;
    }
    return count;
}


SH_API uint64_t ShFindComponent(uint64_t entity,
                                uint32_t classHash)
{
    uint64_t arr;
    uint16_t n = 0, i;

    if (!entity || !ShReadableAddr(entity, 0x90)) {
        ShSetError(SH_ERR_NOT_ENTITY);
        return 0;
    }
    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadableAddr(entity + OFF_ENT_NCOMPS, 2)) return 0;
    memcpy(&n, (void *)(uintptr_t)(entity + OFF_ENT_NCOMPS), 2);
    if (!n || n > 512) return 0;

    for (i = 0; i < n; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);
        if (c && ClassHashOf(c) == classHash) return c;
    }
    return 0;
}

SH_API int ShGetEntityKind(uint64_t entity) {
    int k;
    if (!entity || !ShReadableAddr(entity, 0x90)) return SH_KIND_ANY;
    k = KindIndex(entity);
    return k < 0 ? SH_KIND_ANY : g_kinds[k].kind;
}

SH_API const char *ShKindName(int kind) {
    switch (kind) {
    case SH_KIND_PLAYER:    return "Player";
    case SH_KIND_NPC:       return "NPC";
    case SH_KIND_VEHICLE:   return "Vehicle";
    case SH_KIND_DRONE:     return "Drone";
    case SH_KIND_TEAMMATE:  return "Teammate";
    case SH_KIND_TURRET:    return "Turret";
    case SH_KIND_MINE:      return "Mine";
    case SH_KIND_DOOR:      return "Door";
    case SH_KIND_LOOTCHEST: return "LootChest";
    case SH_KIND_OTHER:     return "Other";
    }
    return "Any";
}

static int WorldList(uint64_t *outList, uint32_t *outCount) {
    uint64_t mgr, world, lst;
    uint16_t n = 0;

    mgr = ShReadQ(ImgAddr(RVA_PLAYER_MGR));
    if (!mgr) return 0;
    world = ShReadQ(mgr + OFF_MGR_WORLD);
    if (!world) return 0;
    lst = ShReadQ(world + OFF_WORLD_LIST);
    if (!lst || !ShReadableAddr(world + OFF_WORLD_COUNT, 2))
        return 0;
    memcpy(&n, (void *)(uintptr_t)(world + OFF_WORLD_COUNT), 2);
    if (!n || n > 4096) return 0;
    *outList = lst;
    *outCount = n;
    return 1;
}

SH_API int ShFindEntities(int kind, float radius, uint32_t flags,
                          ShEntity *out, int max) {
    uint64_t lst = 0, vtEnt;
    uint32_t cnt = 0, i;
    ShVec3 me;
    int n = 0;

    if (!out || max <= 0) { ShSetError(SH_ERR_BAD_ARG); return 0; }
    if (!ShRequireInGame()) return 0;
    if (!WorldList(&lst, &cnt)) {
        ShSetError(SH_ERR_NO_GLOBAL);
        return 0;
    }
    if (!ShGetPlayerPosition(&me)) return 0;
    if (radius <= 0.0f) radius = 1e9f;
    vtEnt = ImgAddr(RVA_VT_ENTITY);

    /* Keep scanning after the output buffer is full.  The insertion below
     * then retains the nearest `max` entries instead of whichever entries
     * happen to occur first in the engine's world list. */
    for (i = 0; i < cnt; i++) {
        uint64_t e = ShReadQ(lst + (uint64_t)i * 8);
        float p[3], dx, dy, dz, d;
        uint32_t cur = 0, mx = 0;
        int ki, j;

        if (!e || !ShReadableAddr(e, 0x90)) continue;
        if (ShReadQ(e) != vtEnt) continue;
        memcpy(p, (void *)(uintptr_t)(e + OFF_ENT_POS), 12);
        dx = p[0] - me.x;
        dy = p[1] - me.y;
        dz = p[2] - me.z;
        d = sqrtf(dx * dx + dy * dy + dz * dz);
        if (d > radius) continue;

        /* Skip limbs, they are parts of a listed entity. */
        if (!IsRoot(e)) continue;

        ki = KindIndex(e);
        if (ki < 0 && !(flags & SH_FIND_UNNAMED)) continue;
        if (kind != SH_KIND_ANY
            && (ki < 0 || g_kinds[ki].kind != kind)) continue;

        ShGetHealthEntity(e, &cur, &mx);

        /* Insertion sort, nearest first. */
        for (j = n; j > 0 && out[j - 1].distance > d; j--)
            if (j < max) out[j] = out[j - 1];
        if (j >= max) continue;
        out[j].entity = e;
        out[j].pos.x = p[0];
        out[j].pos.y = p[1];
        out[j].pos.z = p[2];
        out[j].distance = d;
        out[j].kind = ki < 0 ? SH_KIND_ANY : g_kinds[ki].kind;
        out[j].maxHealth = mx;
        memset(out[j].name, 0, sizeof(out[j].name));
        if (ki >= 0)
            strncpy(out[j].name, g_kinds[ki].name,
                    sizeof(out[j].name) - 1);
        if (n < max) n++;
    }
    ShSetError(SH_OK);
    return n;
}
